local GSE = GSE
local Statics = GSE.Static

Statics.Patrons = {
    "'William Meringolo",
    "900obzen ",
    "A Four",
    "AJ Guckian",
    "AL",
    "ARTEX",
    "Aamir Shakir",
    "Aaron Halpin",
    "Aaron Smith",
    "Aaron Steley",
    "Abnerdoon",
    "Adaestra ",
    "Adam Anderson",
    "Adam Doherty",
    "Adam Fisher",
    "Adam Tall",
    "Adrian Maier",
    "Adventures Of Raven",
    "Aiden Gramson",
    "Akk",
    "Alejandro Sanclemente",
    "Alex",
    "Alex Branch",
    "Allan Korsgaard",
    "Allan Smith Nielsen",
    "Allen Ampueda",
    "Andre Carbonell",
    "Andrew Baldwin",
    "Andrew Fox",
    "Andrew Lester",
    "Andrew VanArman",
    "Andris Kulmans",
    "Andy Dalmat",
    "Andy Erickson",
    "Angel Marchini",
    "Angrypug",
    "AnjosRodrigo",
    "Anthony",
    "Antti Rautio",
    "Anubikk ",
    "Arne Krüger",
    "Ashley",
    "Ashley Ludwig",
    "Ashneel Kumar",
    "Austin Crain",
    "Axellis ",
    "BAO D LE",
    "BRIAN V DELLER",
    "Badcat",
    "Baely ",
    "Baka Pixel",
    "Bear",
    "Bearded_Gamer ",
    "Ben Hocking",
    "Ben Stage",
    "Bengt Grahl",
    "Bennyfof",
    "Beta",
    "Bghy Rbfch",
    "BigPoppaRich",
    "Billy ",
    "Binary Nick",
    "Bitto",
    "Bob",
    "Bobbi Queen",
    "Brad ",
    "Brandon Bks",
    "Brandon Conklin",
    "Brandon Crose",
    "Brett Warfle",
    "Brian",
    "Brian Dickerson",
    "Brian Lewin",
    "Brian Lynch",
    "Brian Miller",
    "Bruce Wardle",
    "Bryan Burns",
    "Bryan Ingram",
    "Bryan Seitz",
    "Burt Reynolds",
    "Cabiria-Il-Notte ",
    "Calvin Jones",
    "Card Cracking Chef",
    "Carlos Alberto Arizpe Mendoza",
    "Carter Cross",
    "Cdub3n",
    "Charles",
    "Charles R Tabor",
    "Chase Hoppock",
    "Choco Munday",
    "Chris Bunting",
    "Chris Cordwell",
    "Chris Esparza",
    "Chris G",
    "Chris Jackson",
    "Chris Juengel",
    "Chris Kiatsirikun",
    "Chris Livingston",
    "Christian Mostert",
    "Christopher Lee",
    "Christopher Young",
    "Christos ",
    "Codda Matl",
    "Colm",
    "Constantin Martini",
    "Corey Marchant",
    "Country Creations",
    "Cruelier",
    "DENNIS CHRISTENSEN",
    "DJ",
    "DJ_FingaGunz",
    "DMFerree",
    "Damon Walker",
    "Dan",
    "Dan Inda",
    "Daniel Gabriele",
    "Daniel Kristofersson",
    "Daniel Lange",
    "Daniel Perez",
    "Daniel Sümmchen",
    "Daniel Thomas",
    "Darkane",
    "Darroll Howard",
    "Dave Gordon",
    "David Isburgh",
    "David Rice",
    "David Rose",
    "David Thrower",
    "Deborah Gough",
    "Deezyl Fizzlepop",
    "Denis Samoilov",
    "Derik B Casper",
    "Devin Blair",
    "Diedora",
    "Dieter Cazon",
    "Dirty Apparition",
    "Dominik Krabacher",
    "Donald Easter",
    "Donnie Spencer",
    "Doug Miers",
    "Dredd",
    "Drioz",
    "Dustin Davenport",
    "Dustin Gadd",
    "Dustin W",
    "E Peters",
    "Edgar Dazevedo",
    "Eduard Claassen",
    "Elange4 ",
    "Elfyau",
    "Elgador",
    "Eli Sapanayev",
    "Emanuel Barbi",
    "Emo Mihov",
    "Enmity",
    "Eric Desmarais",
    "Eric Donini",
    "Eric Rainey",
    "Eric Roberts",
    "Eric Sanders",
    "Eric Stoeckel Jr",
    "Eric Vasquez",
    "Eric Vincent",
    "Eric donini",
    "Erin Reymann",
    "Ernest Dolby",
    "Euben Hadd",
    "Eusélie",
    "Everett St.Clair",
    "Excutive Outcome game",
    "Eznoda",
    "FERDIN GONZALEZ",
    "FPSMarcus",
    "FUT_Sovereign ",
    "Fadi Alfadda",
    "Fallens Death",
    "Fangorian_1337",
    "Ferat A",
    "Florin Enache",
    "Francisco Fernandez",
    "Frankie Lee",
    "FyuZ. ",
    "GamingMama56",
    "Gary",
    "Gary Markland",
    "Gendi",
    "Geoff Weinhold",
    "Geoffrey Tang",
    "George McCubbins",
    "Gerald McCandless",
    "Gerardo Oduber",
    "Gianluca Berian",
    "Gilian Bentulan",
    "Glenn van Kooijk",
    "Goregoth",
    "Greg Schmitz",
    "Gregory M",
    "Grifter",
    "Grim",
    "Grumpy British old Gamer",
    "Gustav Gans",
    "Gấu Panda",
    "Hannah Mae",
    "Hansli Peterli",
    "Hayden Dee",
    "Helder Fernandes",
    "Henrik Nielsen",
    "Herbert Besenfelder",
    "Holger",
    "Holli Mcmillen",
    "Hollis Ford",
    "Hugh Judd",
    "Isaiah Lombardy",
    "Ivan Chiu",
    "J G",
    "Jacek Pasławski",
    "Jack Selektion",
    "Jacob Richey",
    "Jakob Andersen",
    "James Beck",
    "James Blamey",
    "James Faircloth",
    "James Turnbull",
    "Jamie Cuomo",
    "Jamie Currier",
    "Jani Kay",
    "Jason ",
    "Jason Cartledge",
    "Jason Johnson",
    "Jason Kartes",
    "Jasper Hengefeld",
    "Jean-Philippe Baril",
    "Jed Lawton",
    "Jeff Berman",
    "Jeff Butler",
    "Jeff Hughes",
    "Jeffrey White",
    "Jennifer Angelidis",
    "Jeremy Grayson",
    "Jeremy Harvey",
    "Jeremy Jones",
    "Jeremy Neumann",
    "Jerrod Linderman",
    "Jerry T",
    "Jessica",
    "Jim",
    "Jim B",
    "Jimmy Tuvebrant",
    "Jinazz",
    "Jodi Meese",
    "Joe Davis",
    "Joe Jackson",
    "Joel D Bailey",
    "Johan Andersson",
    "Johan Lindqvist",
    "Johan wennerström",
    "John Beland",
    "John D Aulbu",
    "John Hoskin",
    "John Martin",
    "John Weeast",
    "John smith",
    "Jon Noland",
    "Jon Waalewyn",
    "Jonathan Devore Scales",
    "Jonathon Finlay",
    "Joseph Lowery",
    "Josh Silvia",
    "Joshua Sawyer",
    "Joshua Stevens",
    "José Carlos Pérez Carreño",
    "Junior Rodriguez",
    "Justin Robertson",
    "K",
    "KJ",
    "KURT MOSS",
    "Kal basra",
    "Karl gregory",
    "Karoldue ",
    "Keith Fults",
    "Keith Kelly",
    "Kelly Morehead",
    "Kemal Tolun",
    "Ken McCune",
    "Kenny Pritchard",
    "Kevin Fellion",
    "Kevin Hare",
    "Kevin Ibrahim",
    "Kevin James",
    "Kevin Kuijer",
    "Khoa Truong",
    "Kickn Chickn",
    "Kiel Arenas",
    "Klaus Dobrzynski",
    "Kourosh Vosough",
    "Kozzen",
    "Kristopher Bowling",
    "Kristopher K.  Sims",
    "Kyle Francis",
    "Lara Marcattili",
    "Larry Hook",
    "Lars Wingemark",
    "Laura A Clegg",
    "Laura Sieloff",
    "Laurie Holmes",
    "Leeloo",
    "Leprona",
    "LivinOnTheCorner",
    "Lori Nincehelser",
    "Luca Migliorini",
    "Luis Flores",
    "Luke Beals",
    "Luke Newland",
    "MVP",
    "Macroholic",
    "Magnerian",
    "Mals",
    "Manuel Nordmeier",
    "Marc allen",
    "Marcus Andesson",
    "Mardy Stevens",
    "Marek Dvořák",
    "Mark",
    "Mark ",
    "Mark Bradley",
    "Mark Robinson",
    "Mark van de Beek",
    "Marshmellow",
    "Martin Needham",
    "Martin Needham",
    "Martin Vines",
    "Mathias Bohman",
    "Mathusala",
    "Matt Surratt",
    "Mauro colombo",
    "Melchy",
    "Melissa N Anderson",
    "Melissa condon",
    "Meph",
    "Mephchens",
    "Mephiroth",
    "Mercurio",
    "Michael",
    "Michael Bailey",
    "Michael Bray",
    "Michael Brodie",
    "Michael H",
    "Michael Irving",
    "Michael Lewis",
    "Michael Mcdaniels",
    "Michael Phillips",
    "Michael R Kauffmann",
    "Michael Schulz",
    "Michael Swancott",
    "Michal Stalanowski",
    "Miethos",
    "Mike",
    "Mike Pegg",
    "Mikkel Juul Jørgensen",
    "Misty Jinn",
    "Mitchell Emberson",
    "MolarMacros",
    "MrDarque",
    "Murat",
    "Murray Technician",
    "Mystik",
    "Nancy Pierson",
    "Naomi McMillan",
    "Nathan Jetson",
    "Nathan Warfield",
    "Nebiros",
    "Neil Blain",
    "Neil C",
    "Nichola Richardson",
    "Nicholas Brown",
    "Nimmerland Gaming [NlG] Brainz",
    "Noneya Biz",
    "Nora Kirschling",
    "NotSure SureNot",
    "Offline",
    "Oliver Berger",
    "Orion8 Junk",
    "Ouya France",
    "Ozzi",
    "PansaJones",
    "Patrick Lüke",
    "Patrick O'Hagan",
    "Paul Guertin",
    "Paul Kingman",
    "Pedro Machado Creste",
    "Penny2",
    "Peter Haugen",
    "Peter McNinch",
    "Peter von der Ahe",
    "Petter Zweidorff",
    "Phat Le",
    "Phil ",
    "Pippa Martel",
    "Possum Jenkins",
    "Pwntatochip",
    "RACHEL liperote",
    "Radioactive Bullfrog",
    "Rakuza yoknomu",
    "Randall Crank",
    "Randy Barton",
    "Randy G",
    "Randy Rushing",
    "Ravn Maniac",
    "Ray Adams",
    "Ray Feliciano",
    "Raymond Monk",
    "Razerwing",
    "Rebecca Gosdin",
    "Renato Freitas",
    "Rene Traue",
    "René Madl",
    "Rhaina",
    "Rickey C",
    "Ricky Woods",
    "Riki Knight",
    "Robert Andersson",
    "Robert Costello",
    "Robert Ellsworth",
    "Robert Harris",
    "Robert J MacLeod",
    "Robert MacLeod",
    "Robert Mcknight",
    "Robert Pipan",
    "Robert Wears",
    "Robert Webb",
    "Robertas Suminskas",
    "Roberto Roeschmann",
    "Roberto Zanini",
    "Robin Laubinger",
    "Rodrigo Maria Soares",
    "Rodrigo Mendoza",
    "Rody z",
    "Roger Heiniluoma",
    "Rolandas Normanas",
    "RoleClass ",
    "Ronald De Martines",
    "Ronnie Otterborg",
    "Ronny Sæle",
    "Russell Baker",
    "Russell Lee Laymance",
    "Ryan ",
    "Ryan Hickey",
    "Ryan Roberts",
    "Ryo",
    "S Driggers",
    "Samma",
    "Samuel Lacerda",
    "Samuel Spencer",
    "Sandra Primm",
    "Sandy (AKA SassyGamer)",
    "Scarlett Knight",
    "ScaryLarryGames",
    "Schiwouna Schi",
    "Scott Davis",
    "Scott Flippo",
    "Scott Hounsell",
    "Scott Penney",
    "Scott Rose",
    "Scotty",
    "Sean-Heidi Serraguard",
    "Sebastian Kieback",
    "Sergey Droba",
    "ShadyLucifer ",
    "Shane Kuchler",
    "Shaun Baxter",
    "Shaun Flagel",
    "Shelltoekicks",
    "Short",
    "Shtev",
    "Sid Robichaud",
    "Sillk",
    "Simon Karlskov",
    "Simon Wilcock",
    "Sol LeTaire",
    "Solltex ",
    "Sparrowhawk Sr",
    "Spencer Blomquist",
    "Stefan Hauck",
    "Stefano Filardo",
    "Stephen Seagrave",
    "Sternwind",
    "Steve Clink",
    "Steve Hensch",
    "Steven Hansen",
    "Steven Shaw",
    "Steven Short",
    "Steven funnell",
    "Stew Frei",
    "Stormy",
    "Stuart Hendrie",
    "Supbear ",
    "Susan Mushill",
    "Susan Mushill",
    "Susgaming123",
    "Sydney",
    "Sylvok Wolfrun",
    "T D",
    "Tabby Post",
    "Tad Oleson",
    "Tamara C Duncan ",
    "Tamer Baes",
    "Tawaporah",
    "Terry Musser",
    "The world through my eyes",
    "Thomas Maurdal",
    "Thomas Nicholson",
    "Thomas Rambaut",
    "Thore Kvalheim",
    "Thorn the Fox",
    "Tiegars",
    "Tim Firth",
    "Tim Weiden",
    "Timothy Campbell",
    "Timothy allen patterson",
    "Tituswolfe",
    "Tom Straugh",
    "Tommy ",
    "Tommy Southam",
    "Tommy White",
    "Topcat357",
    "Tor Ove",
    "Torbjörn Jönsson",
    "Toril Harink ",
    "Toto Leo",
    "Toxic",
    "Tracy Howard",
    "Travis ",
    "Travis Delaney",
    "Trevor Gordon",
    "Trevor Harper",
    "Tris",
    "Troy Rooker",
    "Truzedo ",
    "Tsaiko",
    "TwistedSMF ",
    "TwiztidBloom",
    "UhohOreo ",
    "Unktehila Iksar",
    "Valamar",
    "Venni Liimatainen",
    "Victor Hodges",
    "Vince G",
    "Vince Orlando",
    "Vuudi",
    "W Wilson",
    "Walter Beiter",
    "Warren Jumper",
    "Waselbein",
    "William Kelley",
    "William Lee",
    "William P Grady",
    "William Sharp",
    "William Smith",
    "Windfey",
    "Wizard Hayden",
    "Woo Kim",
    "ZaffronStaghelm",
    "Zane Savage",
    "Zoonets",
    "Zu#4997",
    "adam humphreys",
    "alan coutts",
    "ale diki",
    "andy le",
    "antonym29@gmail.com",
    "beat theory",
    "bk",
    "blastingweevil",
    "chris ogle",
    "cloutyTV ",
    "crystaltech",
    "curtis buffum",
    "david hawke",
    "devlik",
    "eren ",
    "evasion",
    "ffcjonny",
    "friedbones",
    "giorgino",
    "impaxx ",
    "james hyatt",
    "james stuart broderick",
    "jamie bradley",
    "jay garcia",
    "jean-marie rossi",
    "joe faultless",
    "kay rennow",
    "kelly jarrell",
    "kristian montevecchi",
    "lloyd spencer",
    "luc janssens",
    "manuel Leistner",
    "mika ai",
    "mike sano",
    "mike saul",
    "mourad abrahim",
    "mr mods",
    "neofodder",
    "pantinhatv",
    "pascalmaramis",
    "patrice heinemann",
    "paytun",
    "quoc nguyen",
    "ralf heckel",
    "rightonetwo",
    "ryan kloepper",
    "sten",
    "stiph curry",
    "todd greaves",
    "ttplank",
    "twmwalters",
    "wouZAR ",
    "wynne clark",
    "xManiac",
    "xan2622",
    "zibiken",
    "Александр Кузьмин",
    "مشعل العنزي",
    "熙 凌"
}