local _, addonTable = ...;

addonTable.AllON = {
	["Error"] = {
		["ErrorInfo"] = {},
		["ErrorTishi"] = false,
	},
	["TradePlus"] = {
		["Open"] = true,
	},
	["SkillFBCD"] = {
		["Open"] = true,
		["AddBut"] = true,
		["SkillCD"] = {
		},
		["FubenCD"] = {
		},
	},
	["AutoSellBuy"] = {
		["Open"] = true,
		["AddBut"] = true,
		["Diuqi_Tishi"]=false,
		["Diuqi_List"] = {},
		["Sell_Open"]=true,
		["Sell_But"]=true,
		["Sell_Tishi"]=true,
		["Sell_List"]={},
		["Buy_Open"]=true,
		["Buy_But"]=true,
		["Buy_Tishi"]=true,
		["Open_QkBut"] = true,
		["Open_List"] = {},
		["Fen_QkBut"] = true,
		["Fen_List"] = {},
	},
	["AHPlus"]={
		["Open"] = true,
		["AHtooltip"] = true,
		["Time"] = 48,
		["Tokens"] = {},
		["Coll"] = {},
		["Data"] = {},
		["DaojiTime"] = 0,
		["yajingbiao"] = true,
	},
	["Interaction"] = {
		["Autoloot"] = true,
		["AutoDown"] = true,
		["AutoDialogue"]=true,
		["AutoJierenwu"]=true,
		["AutoJiaorenwu"]=true,
		["AutoJyaoqing"]=false,
		["AutoFuhuo"]=false,
		["AutoRepair"] = true,
		["AutoRepair_GUILD"]=true,
		["RightPlus"] = true,
		["xiayijuli"]=0,
	},
	["QuickFollow"] = {
		["QuickBut"] = true,
		["Name"] = "猪猪加油",
		["Kaishi"] = "1",
		["Jieshu"] = "2",
		["Duizhang"] = true,
		["Tishi"] = true,
		["Qiangli"]=true,
		["Jiuwei"] = true,
		["Yijiao"]=true,
	},
	["Other"] = {
		["ErrorsHide"]=false,
		["PigLoad"]=false,
		["AFK"]={
			["Open"] = false,
			["QuickBut"]=true,
		},
	},
	["Chat"] = {
		["ShowZb"]=true,
		["LinkShow"]=false,
		["Jianyin"] = false,
		["AltEX"] = false,
		["Guolv"] = false,
		["QuickChat"] = true,
		["QuickChat_style"]=1,
		["QuickChat_maodian"] = 1,
		["MinMaxB"] = false,
		["FontSize"] = false,
		["FontSize_value"] = 12,
		["JoinPindao"] = true,
		["jingjian"] = true,
		["TABqiehuanOpen"] = true,
		["TABqiehuanList"] = {},
		["chatZhanlian"] = {},
		["gaoduH"] = 150,
		["BgColor"] = {0,0,0,0.5},
		["guolvzishen"]=false,
		["xitongjihuoB"]=false,
		["guolvchongfu"]=false,
		["KeywordFShow"]=false,
		["Keyword"]={},
		["Blacklist"]={},
		["Frame"] = {
			["Bianju"] = true,
			["Width"] = false,
			["Width_value"] = 350,
			["Height"] = false,
			["Height_value"] = 180,
			["Point"] = false,
			["Point_X"] = 35,
			["Point_Y"] = 80,
			["Loot_Width"] = false,
			["Loot_Width_value"] = 350,
			["Loot_Height"] = false,
			["Loot_Height_value"] = 180,
			["Loot_Point"] = false,
			["Loot_Point_X"] = 26,
			["Loot_Point_Y"] = 8,
			["ShowChannel"] = true,
		},
	},
	["Chatjilu"] = {
		["tianshu"]=7,
		["jiluinfo"]={
			["WHISPER"]={["kaiguan"]=true,["tixing"]=true,["neirong"]={}},
			["PARTY"]={["kaiguan"]=true,["tixing"]=false,["neirong"]={}},
			["RAID"]={["kaiguan"]=true,["tixing"]=false,["neirong"]={}},
		},
	},
	["ActionBar"] = {
		["Ranse"] = true,
		["Cailiao"] = true,
		["PetTishi"] = true,
		["AutoFanye"] = false,
		["HideShijiu"] = true,
		["BarRight"] = true,
		["ActionBar_bili"]=true,
		["ActionBar_bili_value"]=0.8,
		-- ["MenuBag"] = false,
		-- ["MenuBag_bili_value"]=0.9;
	},
	["QuickBut"]={
		["Open"] = true,
		["Point"]={"BOTTOM","BOTTOM",200,200},
		["bili"]=1,
		["Lock"]=false,
		["BGbroadcast"]=true,
		["Lushi"]=true,
		["Spell"]=true,
		["AutoEquip"]=true,
	},
	["BagBank"]={
		["BagKongyu"]=true,
		["Zhenghe"] = true,
		["SortBagsRightToLeft"] = false,
		["JianjieMOD"] = false,
		["hulueBAG"] = {false,false,false,false,false},
		["hulueBANK"] = {false,false,false,false,false,false,false,false},
		["lixian"] = {},
		["SortBag_Config"]=true,
		["qitashulaing"]=false,
		["qitajinbi"]=true,
		["wupinLV"]=true,
		["JunkShow"]=true,
		["BAGmeihangshu"]=8,
		["BAGmeihangshu_retail"]=10,
		["BAGsuofangBili"]=1,
		["BANKmeihangshu"]=16,
		["BANKmeihangshu_retail"]=18,
		["BANKsuofangBili"]=1,
		["jiaoyiOpen"]=true,
		["AHOpen"]=true,
		["wupinRanse"]=true,
	},
	["FramePlus"] = {
		["BuffTime"] = true,
		["Talent"] = true,
		["Skill"] = true,
		["Skill_QKbut"]=true,
		["Quest"] = true,
		["Zhuizong"] = true,
		["Character_xiuliG"] = true,
		["Character_naijiu"] = true,
		["Character_ItemLevel"]=true,
		["Character_ItemColor"]=true,
		["Character_ItemList"]=true,
		["Character_Shuxing"] = true,
		["Character_Mingzhong"] = true,
		["yidongUI"] = true,
	},
	["Tooltip"] = {
		["ItemSell"] = true,
		["ItemLevel"] = true,
		["SpellID"] = true,
	},
	["UnitFrame"] = {
		["PlayerFrame"] = {
			["Plus"] = true,
			["Loot"] = true,
			["HPFF"] = true,	
		},
		["TargetFrame"] = {
			["Plus"] = true,
			["Chouhen"] = true,
			["ToToToT"] = true,
			["Yisu"] = true,
			["BigDebuff"] = false,
		},
		["PartyMemberFrame"] = {
			["Plus"] = true,
		},
	},
	["CombatPlus"] = {
		["Biaoji"] = {
			["Open"] = true,
			["Lock"] = false,
			["BGHide"] = true,
			["AutoShow"] = false,
			["Scale"]=1,
		},
		["CombatTime"]={
			["Open"] = true,
			["Miaobian"]="OUTLINE",
			["Beijing"]=1,
			["Scale"]=1,
		},
		["HPMPBar"]={
			["Open"] = true,
			["Showshuzhi"]=true,
			["Fuziyuan"]=true,
			["CombatShow"]=true,
			["Scale"]=1,
			["Xpianyi"]=0,
			["Ypianyi"]=-80,
		},
	},
	["Map"] = {
		["MinimapBpaichu"] = {},
		["MinimapPos"] = -13.62698465698976,
		["MinimapBut"] = true,
		["MinimapShouNa"] = true,
		["MinimapShouNa_hang"] = 5,
		["MinimapShouNa_BS"] = false,
		["WorldMapBili"] = 0.8,
		["WorldMapPlus"] = false,
		["WorldMapWind"] = true,
		["WorldMapXY"] = true,
		["WorldMapLV"] = true,
		["WorldMapSkill"] = true,
		["WorldMapMiwu"] = true,
		["WorldMapFuben"] = true,
		["WorldMapNPC"] = true,
	},
	["CVars"]={
		["MaxZoom"]= true,
		["AutoCombatLog"]= false,
		["AutoCombatLogTJ"]= 3,
	},
	["RaidRecord"] = {
		["Open"] = true,
		["AddBut"] = true,
		["Rsetting"] ={
			["autofen"]=false,
			["bobaomingxi"] = true,
			["liupaibobao"] = true,
			["liupaichuli"]="组织者自行处理",
			["Pchujia"]="无效",
			["caizhixiufu"] = false,
			["jiaoyidaojishi"] = true,
			["shoudongloot"] = true,
			["fubenwai"] = false,
			["wurenben"] = false,
			["jiaoyijilu"] = true,
			["jiaoyitonggao"] = true,
			["zidonghuifuYY"]=false,
			["YYguanjianzi"]={"YY","yy","歪歪"},
			["YYneirong"]="YY频道:113213,组人不易,请耐心等待",
			["PaichuList"]={},
		},
		["instanceName"]={},
		["LootQuality"]=3,
		["ItemList"]={},
		["Raidinfo"] = {{},{},{},{},{},{},{},{}},
		["Dongjie"] = false,
		["jiangli"]={
			{RAID_LEADER,0,"N/A",false},
			{HEALS.."第一",0,"N/A",false},
			{HEALS.."第二",0,"N/A",false},
			{HEALS.."第三",0,"N/A",false},
			{DAMAGE.."第一",0,"N/A",false},
			{DAMAGE.."第二",0,"N/A",false},
			{DAMAGE.."第三",0,"N/A",false},
		},
		["fakuan"]={
			{"包地板出价",0,"N/A",0},
			{"指挥失误罚款",0,"N/A",0},
			{"跑位失误罚款1",0,"N/A",0},
			{"跑位失误罚款2",0,"N/A",0},
			{"跑位失误罚款3",0,"N/A",0},
			{"ADD罚款1",0,"N/A",0},
			{"ADD罚款2",0,"N/A",0},
			{"ADD罚款3",0,"N/A",0},
		},
		["History"]={},
	},
	["Invite"]={
		["Open"] = true,
		["AddBut"] = true,
		["Plane"]={
			["AutoInvite"]=true,
			["DaojishiCD"]=0,
			["InfoList"]={},
		},
	},
};
addonTable.AllON_Per = {
	["AutoSellBuy"] = {
		["Buy_List"]={},
	},
	["QuickFollow"]={
		["beidongOpen"]=false,
	},
	["PigAction"] = {
		["Open"] = {false,false,false,false},
		["Lock"] = {false,false,false,false},
		["Pailie"] = {1,1,1,1},
		["ShowTJ"] = {1,1,1,1},
		["ActionInfo"] = {},
	},
	["QuickBut"]={
		["ActionInfo"] = {},
		["AutoEquipList"]={},
	},
};