------------------------------------------------------
-- Drops.lua
------------------------------------------------------
-- REFERENCE: [Label] UiMapID, X, Y , A -- Text 
------------------------------------------------------

FT_VendorLocations["Drops"] = {
	
	["Avalanchion"] = {1447, nil, nil, FT.MOB_ELITE}, 			-- Azshara
	["Azuregos"] = {1447, nil, nil, FT.MOB_BOSS}, 				-- Azshara
	["Azure Templar"] = {1451, nil, nil, FT.MOB_ELITE},			-- Silithus
	["Balnazzar"] = {329, nil, nil, FT.MOB_BOSS}, 				-- Stratholme
	["Bannok Grimaxe"] = {229, nil, nil, FT.MOB_RARE_ELITE}, 	-- Blackrock Spire
	["Baron Charr"] = {1449, nil, nil, FT.MOB_ELITE}, 			-- Un'Goro Crater
	["Baron Geddon"] = {409, nil, nil, FT.MOB_BOSS},			-- Molten Core
	["Black Dragonspawn"] = {1428, "East & South of map", nil, nil}, -- Burning Steppes
	["Bloodlord Mandokir"] = {309, nil, nil, FT.MOB_BOSS}, 		-- Zul'Gurub
	["Bloodsail"] = {1434, "All Mobs", nil, nil}, 				-- Stranglethorn Vale
	["Boahn"] = {43, "Main cave, outside instance", nil, FT.MOB_RARE_ELITE}, -- Wailing Caverns
	["Bone Witch"] = {533, nil, nil, FT.MOB_RARE},				-- Naxxramas
	["Boss Galgosh"] = {1432, "Ironband's Excavation Site", nil, FT.MOB_RARE},	-- Loch Modan
	["Brack"] = {1436, "Along Coastline", nil, FT.MOB_RARE}, 	-- Westfall
	["Cannon Master Willey"] = {329, nil, nil, FT.MOB_ELITE}, 	-- Stratholme
	["Cenarion Hold Infantry"] = {1451, "Cenarion Hold", nil, FT.MOB_ELITE}, -- Silithus
	["Cobalt Mageweaver"] = {1452, nil, nil, FT.MOB_ELITE}, 	-- Winterspring
	["Cookie"] = {36, nil, nil, FT.MOB_ELITE}, 					-- The Deadmines
	["Crimson Whelp"] = {1437, 61.8, 31.2, nil}, 				-- Wetlands
	["Dalaran Spellscribe"] = {1421, "Random spawn in Ambermill", nil, nil}, -- Silverpine Forest
	["Dalaran Theurgist/Shield Guard"] = {1416, "Around Dalaran", nil, nil}, -- Alterac Mountains
--	["Darkmaster Gandling"] = {1007, nil, nil, FT.MOB_BOSS}, 	-- Scholomance
	["Defias Pirate"] = {36, nil, nil, FT.MOB_ELITE}, 			-- The Deadmines
	["Dreaming Whelp"] = {1435, "Southwest of map", nil, nil}, 	-- Swamp of Sorrows
	["Earthen Templar"] = {1451, nil, nil, FT.MOB_ELITE},		-- Silithus
	["Elder Mystic Razorsnout"] = {1413, "East of Crossroads", nil, FT.MOB_RARE_ELITE}, -- The Barrens
	["Emeriss"] = {0, nil, nil, FT.MOB_BOSS},					-- Random Spawn
	["Emperor Dagran Thaurissan"] = {230, "Final Boss", nil, FT.MOB_ELITE}, -- Blackrock Depths 
	["Fedfennel"] = {1429, "Northwest of Stonecairn Lake", nil, FT.MOB_RARE}, -- Elwynn Forest
	["Fel Steed"] = {33, "The Courtyard", nil, FT.MOB_ELITE}, 	-- Shadowfang Keep
	["Fenros"] = {1431, "West of Darkshire", nil, FT.MOB_RARE}, -- Duskwood
	["Foe Reaper 4000"] = {1436, nil, nil, FT.MOB_RARE}, 		-- Westfall
	["Foreman Marcrid"] = {1422, 48.4, 31.6, FT.MOB_RARE}, 		-- Western Plaguelands
	["Foreman Thistlenettle"] = {36, "Outside instance", nil, FT.MOB_ELITE}, 	-- The Deadmines
	["Frostmaul Giant"] = {1452, 61.0, 72.4, FT.MOB_ELITE}, 	-- Winterspring
	["Gahz'ranka"] = {429, nil, nil, FT.MOB_BOSS}, 				-- Dire Maul
	["Garneg Charskull"] = {1437, "East of Whelgar's Excavation Site", nil, FT.MOB_RARE},	-- Wetlands
	["Gelihast"] = {48, nil, nil, FT.MOB_ELITE}, 				-- Blackfathom Deeps
	["General Drakkisath"] = {229, nil, nil, FT.MOB_BOSS}, 		-- Blackrock Spire
	["Golemagg the Incinerator"] = {409, nil, nil, FT.MOB_BOSS},-- Molten Core
	["Goraluk Anvilcrack"] = {229, nil, nil, FT.MOB_ELITE}, 	-- Blackrock Spire
	["Grizlak"] = {1432, "In cave, North Thelsamar", nil, FT.MOB_RARE},	-- Loch Modan
	["Grizzle"] = {230, "Ring of Law", nil, FT.MOB_ELITE}, 		-- Blackrock Depths 
	["Gyth"] = {229, nil, nil, FT.MOB_ELITE}, 					-- Blackrock Spire
	["Hammered Patron"] = {230, nil, nil, FT.MOB_ELITE}, 		-- Blackrock Depths
	["Hoary Templar"] = {1451, nil, nil, FT.MOB_ELITE},			-- Silithus
	["Hydrospawn"] = {429, nil, nil, FT.MOB_BOSS}, 				-- Dire Maul
	["Kazon"] = {1433, "North Camp", nil, FT.MOB_RARE},			-- Redridge Mountains
	["Lady Anacondra"] = {43, nil, nil, FT.MOB_BOSS}, 			-- Wailing Caverns
	["Large Loch Crocolisk"] = {1432, "Eastside of river", nil, FT.MOB_RARE},	-- Loch Modan
	["Leprithus"] = {1436, nil, nil, FT.MOB_RARE},				-- Westfall
	["Lethon"] = {0, nil, nil, FT.MOB_BOSS},					-- Random Spawn
	["Lo'Grosh"] = {1416, 52.6, 46.2, FT.MOB_RARE},				-- Alterac Mountains
	["Lord Incendius"] = {230, nil, nil, FT.MOB_BOSS}, 			-- Blackrock Depths
	["Lord Malathrom"] = {1431, 25.6, 30.2, FT.MOB_RARE},		-- Duskwood
	["Lord Sakrasis"] = {1434, 28.6, 62.2, FT.MOB_RARE},		-- Stranglethorn Vale
	["Lupos"] = {1431, nil, nil, FT.MOB_RARE},					-- Duskwood
	["Magmadar"] = {409, nil, nil, FT.MOB_BOSS},				-- Molten Core
	["Magosh"] = {1432, "Ironband's Site", nil, FT.MOB_RARE},	-- Loch Modan
	["Maleki the Pallid"] = {329, nil, nil, FT.MOB_BOSS}, 		-- Stratholme
	["Ma'ruk Wyrmscale"] = {1437, 48.0, 74.2, FT.MOB_RARE}, 	-- Wetlands
	["Mazzranache"] = {1412, "Travels center of map", nil, FT.MOB_RARE},	-- Mulgore
	["Mekgineer Thermaplugg"] = {90, nil, nil, FT.MOB_ELITE},	-- Gnomeregan
	["Moam"] = {509, nil, nil, FT.MOB_BOSS}, 					-- Ruins of Ahn'Qiraj
	["Mosh'Ogg Lord"] = {1434, "Ogre Mound", nil, FT.MOB_ELITE},	-- Stranglethorn Vale
	["Mushgog"] = {429, "In Arena", nil, FT.MOB_RARE_ELITE}, 	-- Dire Maul
	["Naraxis"] = {1431, "East of Darkshire", nil, FT.MOB_RARE}, -- Duskwood
	["Nimar the Slayer"] = {1417, "Witherbark Village", nil, FT.MOB_RARE},		-- Arathi Highlands
	["Old Icebeard"] = {1426, 36.6, 53.4, FT.MOB_RARE},			-- Dun Morogh
	["Plugger Spazzring"] = {230, "Grim Guzzler Bar", nil, FT.MOB_ELITE}, 	-- Blackrock Depths
	["Pridewing Patriarch"] = {1442, nil, nil, FT.MOB_RARE},	-- Stonetalon Mountains
	["Princess Tempestria"] = {1452, "Kel'Theril, on the lake", nil, FT.MOB_ELITE},	-- Winterspring
	["Pyromancer Loregrain"] = {230, nil, nil, FT.MOB_RARE_ELITE}, -- Blackrock Depths
	["Quartermaster Zigris"] = {229, nil, nil, FT.MOB_RARE_ELITE}, -- Blackrock Spire
	["Ras Frostwhisper"] = {1007, nil, nil, FT.MOB_ELITE}, 		-- Scholomance
	["Rathorian"] = {1413, 47.6, 19.2, FT.MOB_RARE},			-- The Barrens
	["Ravenclaw Regent"] = {1421, 57.8, 71.6, FT.MOB_RARE}, 	-- Silverpine Forest
	["Ribbly's Crony"] = {230, nil, nil, FT.MOB_ELITE}, 		-- Blackrock Depths
	["Ribbly Screwspigot"] = {230, "Grim Guzzler Bar", nil, FT.MOB_ELITE}, 	-- Blackrock Depths 
	["Rohh the Silent"] = {1433, "East of Map", nil, FT.MOB_RARE},		-- Redridge Mountains
	["Scalding Whelp"] = {1418, nil, nil, nil}, 				-- Badlands
	["Scale Belly"] = {1434, 43.6, 46.6, FT.MOB_RARE},			-- Stranglethorn Vale
	["Scarlet Archmage/Cleric/Curate/Enchanter"] = {1423, nil, nil, FT.MOB_ELITE},		-- Eastern Plaguelands
	["Searing Whelp"] = {1445, nil, nil, nil}, 					-- Dustwallow Marsh
	["Shazzrah"] = {409, nil, nil, FT.MOB_BOSS},				-- Molten Core
	["Singer"] = {1417, "In Barn", nil, FT.MOB_RARE},			-- Arathi Highlands
	["Slark"] = {1436, "Along coast line", nil, FT.MOB_RARE},	-- Westfall
	["Solakar Flamewreath"] = {229, nil, nil, FT.MOB_ELITE}, 	-- Blackrock Spire
	["Southsea Brigand/Cannoneer/Cutthroat"] = {1413, "South of Ratchet", nil, nil},	-- The Barrens
	["Stonearm"] = {1413, "West of Crossroads", nil, FT.MOB_RARE},	-- The Barrens
	["Stonevault Bonesnapper"] = {1418, "South of map", nil, nil}, -- Badlands
	["Taerar"] = {0, nil, nil, FT.MOB_BOSS},					-- Random Spawn
	["Terrowulf Packlord"] = {1440, 50.6, 38.8, FT.MOB_RARE},	-- Ashenvale
	["Tethis"] = {1434, "Gurubashi Arena", nil, FT.MOB_ELITE},	-- Stranglethorn Vale
	["The Duke of Cynders"] = {1451, nil, nil, FT.MOB_ELITE},	-- Silithus
	["The Duke of Fathoms"] = {1451, nil, nil, FT.MOB_ELITE},	-- Silithus
	["The Duke of Shards"] = {1451, nil, nil, FT.MOB_ELITE},	-- Silithus
	["The Duke of Zephyrs"] = {1451, nil, nil, FT.MOB_ELITE},	-- Silithus
	["The Prophet Skeram"] = {531, nil, nil, FT.MOB_BOSS}, 		-- Temple of Ahn'Qiraj
	["The Rake"] = {1412, "Northeast of Thunder Bluff", nil, FT.MOB_RARE},	-- Mulgore
	["The Windreaver"] = {1451, "Northwest of map", nil, FT.MOB_ELITE},		-- Silithus
	["Trigore the Lasher"] = {43, nil, nil, FT.MOB_RARE_ELITE}, -- Wailing Caverns
	["Venture Co. Foreman"] = {1434, 41.6, 41.4, nil}, 			-- Stranglethorn Vale
	["Vipore's Gryphon"] = {1459, nil, nil, nil}, 				-- Alterac Valley
	["Volchan"] = {1427, nil, nil, FT.MOB_RARE_ELITE}, 			-- Searing Gorge
	["Vultros"] = {1436, nil, nil, FT.MOB_RARE}, 				-- Westfall
	["Ysondre"] = {0, nil, nil, FT.MOB_BOSS},					-- Random Spawn
	
};
