local addonName, addonTable = ...;
local L=addonTable.locale
local _, _, _, tocversion = GetBuildInfo()
local gsub = _G.string.gsub 
local sub = _G.string.sub
local find = _G.string.find
-- --================================
local Create=addonTable.Create
local PIGFrame=Create.PIGFrame
local PIGLine=Create.PIGLine
local PIGEnter=Create.PIGEnter
local PIGButton = Create.PIGButton
local PIGDownMenu=Create.PIGDownMenu
local PIGSlider = Create.PIGSlider
local PIGCheckbutton=Create.PIGCheckbutton
local PIGCheckbutton_R=Create.PIGCheckbutton_R
local PIGOptionsList=Create.PIGOptionsList
local PIGOptionsList_RF=Create.PIGOptionsList_RF
local PIGOptionsList_R=Create.PIGOptionsList_R
local PIGFontString=Create.PIGFontString
local PIGFontStringBG=Create.PIGFontStringBG
local PIGModCheckbutton=Create.PIGModCheckbutton
local PIGQuickBut=Create.PIGQuickBut
local PIGCloseBut=Create.PIGCloseBut
---
local RaidRFun={}
local GnName,GnUI,GnIcon,FrameLevel = L["RaidR_TABNAME"],"RaidR_UI",133742,50
RaidRFun.GnName=GnName
RaidRFun.GnUI=GnUI
RaidRFun.GnIcon=GnIcon
local fuFrame = PIGOptionsList(GnName,"EXT")
-- --
-- local Tooltip = "一个方便团长开团小工具，包括副本掉落记录，补助/罚款记录，便捷物品拍卖，分G助手"
-- fuFrame.Open = PIGModCheckbutton(fuFrame,{GnName,Tooltip},{"TOP",fuFrame,"TOP",0,-10},true)
-- fuFrame.Open:SetScript("OnClick", function (self)
-- 	if self:GetChecked() then
-- 		PIGA["RaidRecord"]["Open"]=true;
-- 		fuFrame.SetListF:Show()
-- 		RaidRFun.RaidRecord()
-- 	else
-- 		PIGA["RaidRecord"]["Open"]=false;
-- 		fuFrame.SetListF:Hide()
-- 		Pig_Options_RLtishi_UI:Show()
-- 	end
-- 	QuickButUI.RaidRecord()
-- end);
-- fuFrame.Open.QKBut:SetScript("OnClick", function (self)
-- 	if self:GetChecked() then
-- 		PIGA["RaidRecord"]["AddBut"]=true
-- 		QuickButUI.RaidRecord()
-- 	else
-- 		PIGA["RaidRecord"]["AddBut"]=false
-- 		Pig_Options_RLtishi_UI:Show();
-- 	end
-- end);
function QuickButUI:RaidRecord()	
	if PIGA["QuickBut"]["Open"] and PIGA["RaidRecord"]["Open"] and PIGA["RaidRecord"]["AddBut"] then
		local QkButUI = "QkBut_RaidRecord"
		if _G[QkButUI] then return end
		local QuickTooltip = "点击-|cff00FFFF打开"..GnName.."|r"
		local QkBut=PIGQuickBut(QkButUI,QuickTooltip,GnIcon,nil,FrameLevel)
		QkBut:SetScript("OnClick", function(self,button)
			if _G[GnUI]:IsShown() then
				_G[GnUI]:Hide();
			else
				_G[GnUI]:Show()
			end
		end);
	end
end
-- ---重置配置
-- fuFrame.Default = PIGButton(fuFrame,{"TOPRIGHT",fuFrame,"TOPRIGHT",-20,-20},{80,22},"重置配置");  
-- fuFrame.Default:SetScript("OnClick", function ()
-- 	StaticPopup_Show ("HUIFU_DEFAULT_FUBEN");
-- end);
-- StaticPopupDialogs["HUIFU_DEFAULT_FUBEN"] = {
-- 	text = "此操作将\124cffff0000重置\124r"..GnName.."所有配置，需重载界面。\n确定重置?",
-- 	button1 = "确定",
-- 	button2 = "取消",
-- 	OnAccept = function()
-- 		PIGA["RaidRecord"] = addonTable.Default["RaidRecord"];
-- 		PIGA["RaidRecord"]["Open"] = true;
-- 		ReloadUI()
-- 	end,
-- 	timeout = 0,
-- 	whileDead = true,
-- 	hideOnEscape = true,
-- }
-- fuFrame:HookScript("OnShow", function (self)
-- 	self.Open:SetChecked(PIGA["RaidRecord"]["Open"])
-- 	self.Open.QKBut:SetChecked(PIGA["RaidRecord"]["AddBut"])
-- 	if PIGA["RaidRecord"]["Open"] then
-- 		self.SetListF:Show()
-- 	else
-- 		self.SetListF:Hide()
-- 	end
-- end);
-- ---------========
-- fuFrame.SetListline = PIGLine(fuFrame,"TOP",-66)
-- fuFrame.SetListF = PIGFrame(fuFrame)
-- fuFrame.SetListF:SetPoint("TOPLEFT",fuFrame.SetListline,"BOTTOMLEFT",0,0);
-- fuFrame.SetListF:SetPoint("BOTTOMRIGHT",fuFrame,"BOTTOMRIGHT",0,0);
-- -------
-- fuFrame.SetListF.fubenwai = PIGCheckbutton_R(fuFrame.SetListF,{"记录副本外","开启后会记录副本外的拾取信息（默认只记录团队副本内掉落）"},true)
-- fuFrame.SetListF.fubenwai:SetScript("OnClick", function (self)
-- 	if self:GetChecked() then
-- 		PIGA["RaidRecord"]["Rsetting"]["fubenwai"]=true;
-- 	else
-- 		PIGA["RaidRecord"]["Rsetting"]["fubenwai"]=false;
-- 	end
-- end);
-- --5人本
-- fuFrame.SetListF.wurenben = PIGCheckbutton_R(fuFrame.SetListF,{"记录5人本","开启后会记录5人本拾取信息（默认只记录团队副本内掉落）"},true)
-- fuFrame.SetListF.wurenben:SetScript("OnClick", function (self)
-- 	if self:GetChecked() then
-- 		PIGA["RaidRecord"]["Rsetting"]["wurenben"]=true;
-- 	else
-- 		PIGA["RaidRecord"]["Rsetting"]["wurenben"]=false;
-- 	end
-- end);

-- --手动添加物品
-- fuFrame.SetListF.shoudongloot = PIGCheckbutton_R(fuFrame.SetListF,{"手动添加物品","开启后按住shift点击聊天栏物品链接添加物品到拾取目录（注意必须保持拾取目录列表为打开状态）"},true)
-- fuFrame.SetListF.shoudongloot:SetScript("OnClick", function (self)
-- 	if self:GetChecked() then
-- 		PIGA["RaidRecord"]["Rsetting"]["shoudongloot"]=true;
-- 	else
-- 		PIGA["RaidRecord"]["Rsetting"]["shoudongloot"]=false;
-- 	end
-- end);
-- --拾取物品倒计时
-- local function ITEMTimetishi()
-- 	if not InCombatLockdown() then
-- 		if PIGA["RaidRecord"]["Open"] and PIGA["RaidRecord"]["Rsetting"]["jiaoyidaojishi"] then
-- 			if PIGA["RaidRecord"]["instanceName"][1] then
-- 				if GetServerTime()-PIGA["RaidRecord"]["instanceName"][1]<43200 then
-- 					if #PIGA["RaidRecord"]["ItemList"]>0 then
-- 						for i=1,#PIGA["RaidRecord"]["ItemList"],1 do
-- 							if PIGA["RaidRecord"]["ItemList"][i][13] then
-- 								if PIGA["RaidRecord"]["ItemList"][i][8]~="无" or PIGA["RaidRecord"]["ItemList"][i][9]>0 or PIGA["RaidRecord"]["ItemList"][i][14]>0 then--已有成交人/收款/欠款
-- 									PIGA["RaidRecord"]["ItemList"][i][13]=false;
-- 								else
-- 									local yijingguoqu=GetServerTime()-PIGA["RaidRecord"]["ItemList"][i][1];
-- 									if yijingguoqu>7200 then
-- 										PIGA["RaidRecord"]["ItemList"][i][13]=false;	
-- 									elseif yijingguoqu>6600 then
-- 										if PIGA["RaidRecord"]["ItemList"][i][12] then
-- 											if UnitIsGroupLeader("player", "LE_PARTY_CATEGORY_HOME") and IsInRaid("LE_PARTY_CATEGORY_HOME") then
-- 												SendChatMessage("提示：未成交物品"..PIGA["RaidRecord"]["ItemList"][i][2].."可交易时间不足10分钟，请确认物品归属(预估时间仅供参考)！","RAID", nil);
-- 												PIGA["RaidRecord"]["ItemList"][i][12]=false;
-- 											end
-- 										end
-- 									end	
-- 								end
-- 							end
-- 						end
-- 					end
-- 				end
-- 			end	
-- 		end
-- 	end
-- 	C_Timer.After(30,ITEMTimetishi);
-- end
-- fuFrame.SetListF.jiaoyidaojishi = PIGCheckbutton_R(fuFrame.SetListF,{"可交易倒计时通告","启用后，物品可交易时间低于10分钟将会在团队频道提示，预估时间仅供参考\n注意此通告不会在战斗中执行"},true)
-- fuFrame.SetListF.jiaoyidaojishi:SetScript("OnClick", function (self)
-- 	if self:GetChecked() then
-- 		PIGA["RaidRecord"]["Rsetting"]["jiaoyidaojishi"]=true;
-- 	else
-- 		PIGA["RaidRecord"]["Rsetting"]["jiaoyidaojishi"]=false;
-- 	end
-- end);

-- --交易记录==========================================================
-- local jiaoyijiluFFFF = CreateFrame("Frame")
-- C_ChatInfo.RegisterAddonMessagePrefix('!Pig-jiaoyi')
-- jiaoyijiluFFFF:RegisterEvent('CHAT_MSG_ADDON');
-- local guangbopindao="RAID";
-- local jiaoyishujuinfo={{},0,{},0}
-- jiaoyijiluFFFF:SetScript("OnEvent",function (self,event,arg1,arg2,arg3,arg4,arg5)
-- 	if event=="CHAT_MSG_ADDON" then
-- 		local namerealm = GetUnitName("player", true);
-- 		if arg1 == '!Pig-jiaoyi' and arg5 ~= namerealm then
-- 			local wupinID, wanjiaName,jiaoyijine = strsplit("-", arg2);
-- 			-- local _, _, _, wupinID = arg2:find("((.+)姓名)");
-- 			-- local _, _, _, wanjiaName = arg2:find("(姓名(.+)金额)");
-- 			-- local _, _,_, jiaoyijine = arg2:find("(金额(.+))");			  
-- 			for x=1,#PIGA["RaidRecord"]["ItemList"] do
-- 				if tonumber(wupinID)==PIGA["RaidRecord"]["ItemList"][x][11] then
-- 					if PIGA["RaidRecord"]["ItemList"][x][8]=="无" and PIGA["RaidRecord"]["ItemList"][x][9]==0 then
-- 						PIGA["RaidRecord"]["ItemList"][x][8]=wanjiaName;
-- 						PIGA["RaidRecord"]["ItemList"][x][9]=tonumber(jiaoyijine);
-- 						PIGA["RaidRecord"]["ItemList"][x][10]=GetServerTime();
-- 						addonTable.RaidRecord_UpdateItem(Item_Scroll_UI);
-- 						break
-- 					end
-- 				end
-- 			end
-- 	    end
-- 	end
-- 	if event=="TRADE_SHOW" then
-- 		jiaoyishujuinfo={{},0,{},0}
-- 	end
-- 	if event=="TRADE_PLAYER_ITEM_CHANGED" or event=="TRADE_TARGET_ITEM_CHANGED" or event=="TRADE_ACCEPT_UPDATE" or event=="TRADE_MONEY_CHANGED" then
-- 		jiaoyishujuinfo={{},0,{},0}
-- 		for i=1,6 do
-- 			local PPPItemlink = GetTradePlayerItemLink(i);
-- 			if PPPItemlink then
-- 				local PPPname, PPPtexture, PPPquantity = GetTradePlayerItemInfo(i)
-- 				table.insert(jiaoyishujuinfo[1],{PPPItemlink,PPPquantity});
-- 			end
-- 			local TTTItemlink = GetTradeTargetItemLink(i);
-- 			if TTTItemlink then
-- 				local TTTname, TTTtexture, TTTquantity = GetTradeTargetItemInfo(i)
-- 				table.insert(jiaoyishujuinfo[3],{TTTItemlink,TTTquantity});
-- 			end
-- 		end
-- 		jiaoyishujuinfo[2]=GetPlayerTradeMoney();
-- 		jiaoyishujuinfo[4]=GetTargetTradeMoney();
-- 	end
-- 	if event=="UI_INFO_MESSAGE" then
-- 		if arg2=="交易完成" then
-- 			if #jiaoyishujuinfo[1]>1 then
-- 				local fubenzhushou_chenggongjiaoyi = false
-- 				for x=1,#jiaoyishujuinfo[1] do
-- 					local zijiitemID = GetItemInfoInstant(jiaoyishujuinfo[1][x][1]);
-- 					for xx=1,#PIGA["RaidRecord"]["ItemList"] do
-- 						if zijiitemID==PIGA["RaidRecord"]["ItemList"][xx][11] then
-- 							if PIGA["RaidRecord"]["ItemList"][xx][8]=="无" and PIGA["RaidRecord"]["ItemList"][xx][9]==0 then
-- 								fubenzhushou_chenggongjiaoyi = true
-- 								local wanjia = TradeFrameRecipientNameText:GetText()
-- 								PIGA["RaidRecord"]["ItemList"][xx][8]=wanjia;
-- 								addonTable.RaidRecord_UpdateItem(Item_Scroll_UI);
-- 								C_ChatInfo.SendAddonMessage('!Pig-jiaoyi', zijiitemID..'-'..wanjia..'-'..0, guangbopindao);-- 发送此次交易给其他使用者
-- 								if PIGA["RaidRecord"]["Rsetting"]["jiaoyitonggao"] then
-- 									SendChatMessage("!Pig:物品"..jiaoyishujuinfo[1][x][1].."已交予"..wanjia,guangbopindao, nil);
-- 								end
-- 								break
-- 							end
-- 						end
-- 					end
-- 				end
-- 				if fubenzhushou_chenggongjiaoyi then
-- 					print("|cff00FFFF!Pig:|r|cffFFFF00一次交易多件物品请手动输入每件物品的成交价！|r")
-- 				end
-- 			elseif #jiaoyishujuinfo[1]==1 then
-- 				local zijiitemID = GetItemInfoInstant(jiaoyishujuinfo[1][1][1]);
-- 				for x=1,#PIGA["RaidRecord"]["ItemList"] do
-- 					if zijiitemID==PIGA["RaidRecord"]["ItemList"][x][11] then
-- 						if PIGA["RaidRecord"]["ItemList"][x][8]=="无" and PIGA["RaidRecord"]["ItemList"][x][9]==0 then
-- 							local wanjia = TradeFrameRecipientNameText:GetText()
-- 							PIGA["RaidRecord"]["ItemList"][x][8]=wanjia;
-- 							PIGA["RaidRecord"]["ItemList"][x][9]=jiaoyishujuinfo[4]/10000;
-- 							PIGA["RaidRecord"]["ItemList"][x][10]=GetServerTime();
-- 							addonTable.RaidRecord_UpdateItem(Item_Scroll_UI);
-- 							C_ChatInfo.SendAddonMessage('!Pig-jiaoyi', zijiitemID..'-'..wanjia..'-'..(jiaoyishujuinfo[4]/10000), guangbopindao);-- 发送此次交易给其他使用者
-- 							if PIGA["RaidRecord"]["Rsetting"]["jiaoyitonggao"] then
-- 								SendChatMessage("!Pig:物品"..jiaoyishujuinfo[1][1][1].."已交予"..wanjia.."，收到"..floor((jiaoyishujuinfo[4]/10000)).."G",guangbopindao, nil);
-- 							end
-- 							break
-- 						end
-- 					end
-- 				end
-- 			elseif #jiaoyishujuinfo[1]==0 then --补交罚款
-- 				for x=1,#PIGA["RaidRecord"]["fakuan"] do
-- 					local wanjia = TradeFrameRecipientNameText:GetText()
-- 					if PIGA["RaidRecord"]["fakuan"][x][4]==wanjia then
-- 						PIGA["RaidRecord"]["fakuan"][x][2]=PIGA["RaidRecord"]["fakuan"][x][2]+jiaoyishujuinfo[4]/10000;
-- 						if PIGA["RaidRecord"]["fakuan"][x][3]>0 then
-- 							PIGA["RaidRecord"]["fakuan"][x][3]=PIGA["RaidRecord"]["fakuan"][x][3]-jiaoyishujuinfo[4]/10000;
-- 						end
-- 						addonTable.RaidRecord_UpdateFakuan(fakuan_Scroll_UI);
-- 						break
-- 					end
-- 				end
-- 			end
-- 			--从物品目录剔除此次交易生成的拾取记录
-- 			if #jiaoyishujuinfo[3]>0 then
-- 				for x=1,#jiaoyishujuinfo[3] do
-- 					for v = #PIGA["RaidRecord"]["ItemList"], 1, -1 do
-- 						if jiaoyishujuinfo[3][x][1]==PIGA["RaidRecord"]["ItemList"][v][2] then
-- 							table.remove(PIGA["RaidRecord"]["ItemList"],v);
-- 							break
-- 						end
-- 					end
-- 					for d =1, #PIGA["RaidRecord"]["ItemList"] , 1 do
-- 						if jiaoyishujuinfo[3][x][1]==PIGA["RaidRecord"]["ItemList"][d][2] then
-- 							PIGA["RaidRecord"]["ItemList"][d][3]=PIGA["RaidRecord"]["ItemList"][d][3]-jiaoyishujuinfo[3][x][2];
-- 						end
-- 					end
-- 					addonTable.RaidRecord_UpdateItem(Item_Scroll_UI)
-- 				end
-- 			end
-- 		end
-- 	end
-- end)
-- local function jiaoyijiluFun()
-- 	if PIGA["RaidRecord"]["Open"] and PIGA["RaidRecord"]["Rsetting"]["jiaoyijilu"] then
-- 		PIGEnable(fuFrame.SetListF.jiaoyitonggao)
-- 		jiaoyijiluFFFF:RegisterEvent("UI_INFO_MESSAGE");--交易信息
-- 		jiaoyijiluFFFF:RegisterEvent("TRADE_SHOW");
-- 		jiaoyijiluFFFF:RegisterEvent("TRADE_CLOSED");
-- 		--jiaoyijiluFFFF:RegisterEvent("TRADE_REQUEST_CANCEL");--取消交易尝试时触发。
-- 		-- jiaoyijiluFFFF:RegisterEvent("PLAYER_TRADE_MONEY");--当玩家进行交易时被触发
-- 		jiaoyijiluFFFF:RegisterEvent("TRADE_MONEY_CHANGED");--交易窗口的货币值更改时触发。
-- 		jiaoyijiluFFFF:RegisterEvent("TRADE_PLAYER_ITEM_CHANGED");
-- 		jiaoyijiluFFFF:RegisterEvent("TRADE_TARGET_ITEM_CHANGED");
-- 		jiaoyijiluFFFF:RegisterEvent("TRADE_ACCEPT_UPDATE");--当玩家和目标接受按钮的状态更改时触发。
-- 	else
-- 		PIGDisable(fuFrame.SetListF.jiaoyitonggao)
-- 		jiaoyijiluFFFF:UnregisterEvent("UI_INFO_MESSAGE");--交易信息
-- 		jiaoyijiluFFFF:UnregisterEvent("TRADE_SHOW");
-- 		jiaoyijiluFFFF:UnregisterEvent("TRADE_CLOSED");
-- 		--jiaoyijiluFFFF:UnregisterEvent("TRADE_REQUEST_CANCEL");--取消交易尝试时触发。
-- 		-- jiaoyijiluFFFF:UnregisterEvent("PLAYER_TRADE_MONEY");--当玩家进行交易时被触发
-- 		jiaoyijiluFFFF:UnregisterEvent("TRADE_MONEY_CHANGED");--交易窗口的货币值更改时触发。
-- 		jiaoyijiluFFFF:UnregisterEvent("TRADE_PLAYER_ITEM_CHANGED");
-- 		jiaoyijiluFFFF:UnregisterEvent("TRADE_TARGET_ITEM_CHANGED");
-- 		jiaoyijiluFFFF:UnregisterEvent("TRADE_ACCEPT_UPDATE");--当玩家和目标接受按钮的状态更改时触发。
-- 	end
-- end
-- ------------
-- local jiaoyijiluTS="开启后,交易拾取目录内的物品将会自动填入收入金额及成交人。一次交易多件商品只会记录成交人需手动输入每件商品收入价\n|cff00ff00（其他已安装本插件的玩家也会收到此次交易信息）|r"
-- fuFrame.SetListF.jiaoyijilu = PIGCheckbutton_R(fuFrame.SetListF,{"记录装备交易",jiaoyijiluTS},true)
-- fuFrame.SetListF.jiaoyijilu:SetScript("OnClick", function (self)
-- 	if self:GetChecked() then
-- 		PIGA["RaidRecord"]["Rsetting"]["jiaoyijilu"]=true;
-- 	else
-- 		PIGA["RaidRecord"]["Rsetting"]["jiaoyijilu"]=false;
-- 	end
-- 	jiaoyijiluFun()
-- end);
-- fuFrame.SetListF.jiaoyitonggao = PIGCheckbutton_R(fuFrame.SetListF,{"交易通告","通告交易物品和被交易人"},true)
-- fuFrame.SetListF.jiaoyitonggao:SetScript("OnClick", function (self)
-- 	if self:GetChecked() then
-- 		PIGA["RaidRecord"]["Rsetting"]["jiaoyitonggao"]=true;
-- 	else
-- 		PIGA["RaidRecord"]["Rsetting"]["jiaoyitonggao"]=false;
-- 	end
-- end);
-- ----===================================================
-- local waiwaizidonghuifu_fuben = CreateFrame("Frame");
-- local function zhuceshijianEE()
-- 	if PIGA["RaidRecord"]["Rsetting"]["zidonghuifuYY"] then
-- 		waiwaizidonghuifu_fuben:RegisterEvent("CHAT_MSG_WHISPER") 
-- 		waiwaizidonghuifu_fuben:RegisterEvent("CHAT_MSG_PARTY");--收到组队信息
-- 		waiwaizidonghuifu_fuben:RegisterEvent("CHAT_MSG_PARTY_LEADER");
-- 		waiwaizidonghuifu_fuben:RegisterEvent("CHAT_MSG_RAID");--收到团队信息
-- 		waiwaizidonghuifu_fuben:RegisterEvent("CHAT_MSG_RAID_LEADER");
-- 	else
-- 		waiwaizidonghuifu_fuben:UnregisterAllEvents();
-- 	end
-- end
-- fuFrame.SetListF.zidonghuifuYY = PIGCheckbutton_R(fuFrame.SetListF,{"自动回复YY频道\124cff00FF00(你必须是队长或团长)\124r","开启后,收到队伍或者团队人员咨询YY频道会自动回复预设内容"},true)
-- fuFrame.SetListF.zidonghuifuYY:SetScript("OnClick", function (self)
-- 	if self:GetChecked() then
-- 		PIGA["RaidRecord"]["Rsetting"]["zidonghuifuYY"]=true;
-- 	else
-- 		PIGA["RaidRecord"]["Rsetting"]["zidonghuifuYY"]=false;
-- 	end
-- 	zhuceshijianEE()
-- end);

-- --触发关键字
-- fuFrame.SetListF.zidonghuifuYY.biaoti = PIGFontString(fuFrame.SetListF,{"TOPLEFT", fuFrame.SetListF.zidonghuifuYY, "BOTTOMLEFT", 0,-6},"触发关键字(用，分隔):");
-- fuFrame.SetListF.zidonghuifuYY.F = PIGFrame(fuFrame.SetListF,{"TOPLEFT", fuFrame.SetListF.zidonghuifuYY.biaoti, "BOTTOMLEFT", 0,-2},{320,26});
-- fuFrame.SetListF.zidonghuifuYY.F:PIGSetBackdrop()
-- fuFrame.SetListF.zidonghuifuYY.E = CreateFrame('EditBox', nil, fuFrame.SetListF.zidonghuifuYY.F);
-- fuFrame.SetListF.zidonghuifuYY.E:SetPoint("TOPLEFT", fuFrame.SetListF.zidonghuifuYY.F, "TOPLEFT", 8,-6);
-- fuFrame.SetListF.zidonghuifuYY.E:SetPoint("BOTTOMRIGHT", fuFrame.SetListF.zidonghuifuYY.F, "BOTTOMRIGHT", -8,6);
-- fuFrame.SetListF.zidonghuifuYY.E:SetFontObject(ChatFontNormal);
-- fuFrame.SetListF.zidonghuifuYY.E:SetAutoFocus(false);
-- fuFrame.SetListF.zidonghuifuYY.E:SetMaxLetters(22);
-- fuFrame.SetListF.zidonghuifuYY.E:SetTextColor(0.6, 0.6, 0.6, 1);
-- fuFrame.SetListF.zidonghuifuYY.E:SetScript("OnEditFocusGained", function(self) 
-- 	self:SetTextColor(1, 1, 1, 1);
-- end);
-- fuFrame.SetListF.zidonghuifuYY.E:SetScript("OnEscapePressed", function(self) 
-- 	self:ClearFocus() 
-- end);
-- fuFrame.SetListF.zidonghuifuYY.E:SetScript("OnEnterPressed", function(self) 
-- 	self:ClearFocus() 
-- end);
-- local function fengedianjianzi(str,delimiter)
--     local dLen = string.len(delimiter)
--     local newDeli = ''
--     for i=1,dLen,1 do
--         newDeli = newDeli .. "["..delimiter:sub(i,i).."]"
--     end

--     local locaStart,locaEnd = str:find(newDeli)
--     local arr = {}
--     local n = 1
--     while locaStart ~= nil
--     do
--         if locaStart>0 then
--             arr[n] = str:sub(1,locaStart-1)
--             n = n + 1
--         end

--         str = str:sub(locaEnd+1,string.len(str))
--         locaStart,locaEnd = str:find(newDeli)
--     end
--     if str ~= nil and str ~= "" and str ~= " " then
--         arr[n] = str
--     end
--     return arr
-- end
-- fuFrame.SetListF.zidonghuifuYY.E:SetScript("OnEditFocusLost", function(self)
-- 	self:SetTextColor(0.6, 0.6, 0.6, 1);
-- 	local guanjianV = self:GetText();
-- 	local guanjianshuzu = guanjianV:gsub("，", ",")
-- 	local guanjianzilist = fengedianjianzi(guanjianshuzu, ",")
-- 	PIGA["RaidRecord"]["Rsetting"]["YYguanjianzi"]=guanjianzilist;
-- end);
-- --回复内容
-- fuFrame.SetListF.zidonghuifuYY.NR_biaoti = PIGFontString(fuFrame.SetListF,{"TOPLEFT", fuFrame.SetListF.zidonghuifuYY.F, "BOTTOMLEFT", 0,-6},"回复内容:");
-- fuFrame.SetListF.zidonghuifuYY.NR = PIGFrame(fuFrame.SetListF,{"TOPLEFT", fuFrame.SetListF.zidonghuifuYY.NR_biaoti, "BOTTOMLEFT", 0,-2},{320,26});
-- fuFrame.SetListF.zidonghuifuYY.NR:PIGSetBackdrop()
-- fuFrame.SetListF.zidonghuifuYY.NR_E = CreateFrame('EditBox', nil, fuFrame.SetListF.zidonghuifuYY.NR);
-- fuFrame.SetListF.zidonghuifuYY.NR_E:SetPoint("TOPLEFT", fuFrame.SetListF.zidonghuifuYY.NR, "TOPLEFT", 8,-6);
-- fuFrame.SetListF.zidonghuifuYY.NR_E:SetPoint("BOTTOMRIGHT", fuFrame.SetListF.zidonghuifuYY.NR, "BOTTOMRIGHT", -8,6);
-- fuFrame.SetListF.zidonghuifuYY.NR_E:SetFontObject(ChatFontNormal);
-- fuFrame.SetListF.zidonghuifuYY.NR_E:SetAutoFocus(false);
-- fuFrame.SetListF.zidonghuifuYY.NR_E:SetMaxLetters(40);
-- fuFrame.SetListF.zidonghuifuYY.NR_E:SetTextColor(0.6, 0.6, 0.6, 1);
-- fuFrame.SetListF.zidonghuifuYY.NR_E:SetScript("OnEditFocusGained", function(self) 
-- 	self:SetTextColor(1, 1, 1, 1);
-- end);
-- fuFrame.SetListF.zidonghuifuYY.NR_E:SetScript("OnEscapePressed", function(self) 
-- 	self:ClearFocus() 
-- end);
-- fuFrame.SetListF.zidonghuifuYY.NR_E:SetScript("OnEnterPressed", function(self) 
-- 	self:ClearFocus() 
-- end);
-- fuFrame.SetListF.zidonghuifuYY.NR_E:SetScript("OnEditFocusLost", function(self)
-- 	self:SetTextColor(0.6, 0.6, 0.6, 1);
-- 	PIGA["RaidRecord"]["Rsetting"]["YYneirong"]=self:GetText();
-- end);
-- ---
-- waiwaizidonghuifu_fuben:SetScript("OnEvent",function(self, event,arg1,_,_,_,arg5)
-- 	if PIGA["RaidRecord"]["Rsetting"]["zidonghuifuYY"] then
-- 		local isLeader = UnitIsGroupLeader("player", "LE_PARTY_CATEGORY_HOME");
-- 		if isLeader then
-- 			local nameziji = UnitName("player")
-- 			if arg5~=nameziji then
-- 				local fubenzhushou_zidonghuifuYY=arg1:find("[!Pig]", 1)
-- 				if not fubenzhushou_zidonghuifuYY then
-- 					local YYguanjianzi=PIGA["RaidRecord"]["Rsetting"]["YYguanjianzi"];
-- 					for i=1,#YYguanjianzi do
-- 						local YYhaoYES=arg1:find(YYguanjianzi[i], 1)
-- 						if YYhaoYES then
-- 							if event=="CHAT_MSG_WHISPER" then
-- 								local IsInRaid=IsInRaid("LE_PARTY_CATEGORY_HOME");
-- 								if IsInRaid then
-- 									for p=1,40 do
-- 										local name = GetUnitName("raid"..p, true)
-- 										if name~=nil then
-- 											if arg5==name then
-- 												SendChatMessage("[!Pig] "..PIGA["RaidRecord"]["Rsetting"]["YYneirong"], "WHISPER", nil, arg5);
-- 												break
-- 											end
-- 										end
-- 									end
-- 								else
-- 									local IsInGroup = IsInGroup("LE_PARTY_CATEGORY_HOME");
-- 									if IsInGroup then
-- 										for p=1,4 do
-- 											local name = GetUnitName("party"..p, true)
-- 											if name~=nil then
-- 												if arg5==name then
-- 													SendChatMessage("[!Pig] "..PIGA["RaidRecord"]["Rsetting"]["YYneirong"], "WHISPER", nil, arg5);
-- 													break
-- 												end
-- 											end
-- 										end
-- 									end
-- 								end
-- 							elseif event=="CHAT_MSG_PARTY" or event=="CHAT_MSG_PARTY_LEADER" then
-- 								SendChatMessage("[!Pig] "..PIGA["RaidRecord"]["Rsetting"]["YYneirong"], "PARTY", nil);
-- 							elseif event=="CHAT_MSG_RAID" or event=="CHAT_MSG_RAID_LEADER" then
-- 								SendChatMessage("[!Pig] "..PIGA["RaidRecord"]["Rsetting"]["YYneirong"], "RAID_WARNING", nil);
-- 							end
-- 							break
-- 						end
-- 					end
-- 				end
-- 			end
-- 		end
-- 	end
-- end)
-- --=================================================================
-- --过滤排除物品
-- local paichu_Height,paichu_NUM  = 28.4, 15;
-- local function gengxinpaichu(self)
-- 	for k = 1, paichu_NUM do
-- 		_G["PaichuList"..k]:Hide();
--     end
--     local paichumulu = PIGA["RaidRecord"]["Rsetting"]["PaichuList"]
--     local ItemsNum = #paichumulu
-- 	if ItemsNum>0 then
-- 		FauxScrollFrame_Update(self, ItemsNum, paichu_NUM, paichu_Height);
-- 		local offset = FauxScrollFrame_GetOffset(self);
-- 		for k = 1, paichu_NUM do
-- 			local dangqianH = k+offset;
-- 			if paichumulu[dangqianH] then
-- 				local fujik=_G["PaichuList"..k]
-- 				fujik:Show();
-- 				fujik.del:SetID(dangqianH);
-- 				local itemName, itemLink, _, _, _, _, _, _,_, itemTexture=GetItemInfo(paichumulu[dangqianH]);
-- 		    	fujik.item.icon:SetTexture(itemTexture);
-- 				fujik.item.link:SetText(itemLink);
-- 				fujik.item:SetScript("OnMouseDown", function (self)
-- 					GameTooltip:ClearLines();
-- 					GameTooltip:SetOwner(self, "ANCHOR_CURSOR");
-- 					GameTooltip:SetHyperlink(itemLink)
-- 				end);
-- 				fujik.item:SetScript("OnMouseUp", function ()
-- 					GameTooltip:ClearLines();
-- 					GameTooltip:Hide() 
-- 				end);
-- 			end
-- 		end
-- 	end
-- end
-- -----------
-- fuFrame.SetListF.Paichu = PIGFrame(fuFrame.SetListF,{"TOPLEFT", fuFrame.SetListF, "TOPRIGHT", -260, -28})
-- fuFrame.SetListF.Paichu:SetPoint("BOTTOMRIGHT", fuFrame.SetListF, "BOTTOMRIGHT", -6, 6)
-- fuFrame.SetListF.Paichu:PIGSetBackdrop()
-- fuFrame.SetListF.Paichu.biaoti = fuFrame.SetListF.Paichu:CreateFontString();
-- fuFrame.SetListF.Paichu.biaoti:SetPoint("BOTTOMLEFT", fuFrame.SetListF.Paichu, "TOPLEFT", 4, 4);
-- fuFrame.SetListF.Paichu.biaoti:SetFont(ChatFontNormal:GetFont(), 14, "OUTLINE");
-- fuFrame.SetListF.Paichu.biaoti:SetText("\124cff00FF00忽略以下物品拾取记录\124r");
-- --提示
-- fuFrame.SetListF.Paichu.biaoti_tishi = CreateFrame("Frame", nil, fuFrame.SetListF.Paichu);
-- fuFrame.SetListF.Paichu.biaoti_tishi:SetSize(30,30);
-- fuFrame.SetListF.Paichu.biaoti_tishi:SetPoint("LEFT",fuFrame.SetListF.Paichu.biaoti,"RIGHT",-6,0);
-- fuFrame.SetListF.Paichu.biaoti_tishi.Tex = fuFrame.SetListF.Paichu.biaoti_tishi:CreateTexture(nil, "BORDER");
-- fuFrame.SetListF.Paichu.biaoti_tishi.Tex:SetTexture("interface/common/help-i.blp");
-- fuFrame.SetListF.Paichu.biaoti_tishi.Tex:SetAllPoints(fuFrame.SetListF.Paichu.biaoti_tishi)
-- PIGEnter(fuFrame.SetListF.Paichu.biaoti_tishi,"提示：","\124cff00ff00拾取记录页面右键点击物品名添加为不记录.\124r")
-- ----可滚动区域
-- fuFrame.SetListF.Paichu.Scroll = CreateFrame("ScrollFrame",nil,fuFrame.SetListF.Paichu, "FauxScrollFrameTemplate");  
-- fuFrame.SetListF.Paichu.Scroll:SetPoint("TOPLEFT",fuFrame.SetListF.Paichu,"TOPLEFT",0,0);
-- fuFrame.SetListF.Paichu.Scroll:SetPoint("BOTTOMRIGHT",fuFrame.SetListF.Paichu,"BOTTOMRIGHT",-25,2);
-- fuFrame.SetListF.Paichu.Scroll:SetScript("OnVerticalScroll", function(self, offset)
--     FauxScrollFrame_OnVerticalScroll(self, offset, Paichu_Height, gengxinpaichu)
-- end)
-- --创建行
-- local Paichuww = fuFrame.SetListF.Paichu:GetWidth()
-- for id = 1, paichu_NUM do
-- 	local Pcwupin = CreateFrame("Frame", "PaichuList"..id, fuFrame.SetListF.Paichu.Scroll:GetParent());
-- 	Pcwupin:SetSize(Paichuww-25, paichu_Height);
-- 	if id==1 then
-- 		Pcwupin:SetPoint("TOP",fuFrame.SetListF.Paichu.Scroll,"TOP",0,0);
-- 	else
-- 		Pcwupin:SetPoint("TOP",_G["PaichuList"..(id-1)],"BOTTOM",0,-0);
-- 	end
-- 	if id~=paichu_NUM then
-- 		Pcwupin.line = PIGLine(Pcwupin,"BOT")
-- 	end
-- 	Pcwupin.del=PIGCloseBut(Pcwupin,{"LEFT", Pcwupin, "LEFT", 4,0},{22,22})
-- 	Pcwupin.del:SetScript("OnClick", function (self)
-- 		table.remove(PIGA["RaidRecord"]["Rsetting"]["PaichuList"], self:GetID());
-- 		gengxinpaichu(fuFrame.SetListF.Paichu.Scroll);
-- 	end);
-- 	Pcwupin.item = CreateFrame("Frame", nil, Pcwupin);
-- 	Pcwupin.item:SetSize(Paichuww-51,paichu_Height);
-- 	Pcwupin.item:SetPoint("LEFT",Pcwupin.del,"RIGHT",0,0);
-- 	Pcwupin.item.icon = Pcwupin.item:CreateTexture(nil, "BORDER");
-- 	Pcwupin.item.icon:SetSize(paichu_Height-4,paichu_Height-4);
-- 	Pcwupin.item.icon:SetPoint("LEFT", Pcwupin.item, "LEFT", 0,0);
-- 	Pcwupin.item.link = PIGFontString(Pcwupin.item,{"LEFT", Pcwupin.item.icon, "RIGHT", 1,0});
-- end
-- --=============================
-- fuFrame.SetListF:HookScript("OnShow", function (self)
-- 	fuFrame.SetListF.jiaoyidaojishi:SetChecked(PIGA["RaidRecord"]["Rsetting"]["jiaoyidaojishi"]);
-- 	fuFrame.SetListF.fubenwai:SetChecked(PIGA["RaidRecord"]["Rsetting"]["fubenwai"]);
-- 	fuFrame.SetListF.wurenben:SetChecked(PIGA["RaidRecord"]["Rsetting"]["wurenben"]);
-- 	fuFrame.SetListF.shoudongloot:SetChecked(PIGA["RaidRecord"]["Rsetting"]["shoudongloot"]);
-- 	fuFrame.SetListF.jiaoyijilu:SetChecked(PIGA["RaidRecord"]["Rsetting"]["jiaoyijilu"]);
-- 	fuFrame.SetListF.jiaoyitonggao:SetChecked(PIGA["RaidRecord"]["Rsetting"]["jiaoyitonggao"]);
-- 	fuFrame.SetListF.zidonghuifuYY:SetChecked(PIGA["RaidRecord"]["Rsetting"]["zidonghuifuYY"]);
-- 	local huifuYY_guanjianzineirong="";
-- 	for i=1,#PIGA["RaidRecord"]["Rsetting"]["YYguanjianzi"] do
-- 		if i~=#PIGA["RaidRecord"]["Rsetting"]["YYguanjianzi"] then
-- 			huifuYY_guanjianzineirong=huifuYY_guanjianzineirong..PIGA["RaidRecord"]["Rsetting"]["YYguanjianzi"][i].."，"
-- 		else
-- 			huifuYY_guanjianzineirong=huifuYY_guanjianzineirong..PIGA["RaidRecord"]["Rsetting"]["YYguanjianzi"][i]
-- 		end
-- 	end
-- 	fuFrame.SetListF.zidonghuifuYY.E:SetText(huifuYY_guanjianzineirong)
-- 	fuFrame.SetListF.zidonghuifuYY.NR_E:SetText(PIGA["RaidRecord"]["Rsetting"]["YYneirong"])
-- 	gengxinpaichu(fuFrame.SetListF.Paichu.Scroll);
-- end)
-- ----------------
addonTable.RaidRFun=RaidRFun
addonTable.RaidRecord = function()
	if PIGA["RaidRecord"]["Open"] then
		-- RaidRFun.RaidRecord()
		-- ITEMTimetishi();
		-- jiaoyijiluFun();
		-- zhuceshijianEE()
	end
end